@extends('layouts.app')

@section('title', 'Profit & Loss Statement')

@section('content')
<div class="content-wrapper bg-white min-h-screen pb-20 p-12">
    <!-- Report Branding -->
    <div class="flex justify-between items-start mb-16 border-b-4 border-slate-900 pb-12">
        <div>
            <h1 class="text-6xl font-black text-slate-900 tracking-tighter uppercase italic">Income Statement</h1>
            <p class="text-slate-400 font-black text-lg mt-4 tracking-wider uppercase ml-1">Saxocell Internal Systems • Financial Period: {{ $startDate }} to {{ $endDate }}</p>
        </div>
        <div class="text-right">
            <div class="p-6 bg-slate-900 text-white rounded-[2rem] shadow-2xl">
                <p class="text-xs font-bold uppercase tracking-[0.5em] mb-2 opacity-50">Net Operating Income</p>
                <p class="text-4xl font-black {{ $netProfit >= 0 ? 'text-emerald-400' : 'text-rose-400' }}">RP {{ number_format($netProfit, 0, ',', '.') }}</p>
            </div>
        </div>
    </div>

    <div class="max-w-4xl mx-auto space-y-16">
        <!-- Revenue Section -->
        <div>
            <div class="flex items-end justify-between mb-8 border-b-2 border-slate-100 pb-4">
                <h2 class="text-3xl font-black text-slate-900 uppercase tracking-tighter">I. Total Revenue</h2>
                <span class="text-2xl font-black text-slate-900 underline decoration-slate-200">RP {{ number_format($totalRevenue, 0, ',', '.') }}</span>
            </div>
            <div class="space-y-4 px-6">
                @foreach($revenue as $acc)
                <div class="flex justify-between items-center group">
                    <span class="text-slate-500 font-bold text-lg group-hover:text-slate-900 transition-colors">{{ $acc->name }}</span>
                    <span class="text-slate-900 font-black text-lg">RP {{ number_format($acc->current_balance, 0, ',', '.') }}</span>
                </div>
                @endforeach
            </div>
        </div>

        <!-- Expenses Section -->
        <div>
            <div class="flex items-end justify-between mb-8 border-b-2 border-slate-100 pb-4">
                <h2 class="text-3xl font-black text-slate-900 uppercase tracking-tighter">II. Operating Expenses</h2>
                <span class="text-2xl font-black text-rose-600 underline decoration-rose-100">RP ({{ number_format($totalExpense, 0, ',', '.') }})</span>
            </div>
            <div class="space-y-4 px-6">
                @foreach($expenses as $acc)
                <div class="flex justify-between items-center group">
                    <span class="text-slate-500 font-bold text-lg group-hover:text-slate-900 transition-colors">{{ $acc->name }}</span>
                    <span class="text-slate-900 font-black text-lg">RP {{ number_format($acc->current_balance, 0, ',', '.') }}</span>
                </div>
                @endforeach
            </div>
        </div>

        <!-- Net Result -->
        <div class="pt-12 border-t-8 border-slate-900">
            <div class="flex justify-between items-center p-10 bg-slate-50 rounded-[3rem]">
                <div>
                    <h3 class="text-4xl font-black text-slate-900 uppercase tracking-tighter italic">Net Profit / Loss</h3>
                    <p class="text-slate-400 font-bold text-sm uppercase tracking-wider mt-2">After all operating expenses and income</p>
                </div>
                <div class="text-right">
                    <p class="text-3xl font-bold {{ $netProfit >= 0 ? 'text-emerald-600' : 'text-rose-600' }}">RP {{ number_format($netProfit, 0, ',', '.') }}</p>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Print Footer -->
    <div class="mt-24 text-center">
        <p class="text-slate-300 font-black text-[10px] uppercase tracking-[1em]">Generated by Antigravity Finance System • Confidential Document</p>
    </div>
</div>
@endsection
